const UserConstants = {
    REQUEST: 'REQUEST',
    FAILURE: 'FAILURE',
    SUCCESS: 'SUCCESS'
};

const MailConstants = {
    REQUEST_MAIL: 'REQUEST_MAIL',
    FAILURE_MAIL: 'FAILURE_MAIL',
    SUCCESS_MAIL: 'SUCCESS_MAIL',
    GET_MAIL: 'GET_MAIL',
    GET_NOTIFICATIONS_THREAD: 'GET_NOTIFICATIONS_THREAD',
    GET_THREADS: 'GET_THREADS',
    GET_ESTADOS_ACT: 'GET_ESTADOS_ACT'
}

const ClientConstants = {
    REQUEST_CLIENT: 'REQUEST_CLIENT',
    FAILURE_CLIENT: 'FAILURE_CLIENT',
    SUCCESS_CLIENT: 'SUCCESS_CLIENT',
    GET_CLIENTS: 'GET_CLIENTS',
    GET_CLIENTS_OPERATION: 'GET_CLIENTS_OPERATION',
    GET_CLIENT_ACT: 'GET_CLIENT_ACT',
    GET_PRODUC_CLIENT: 'GET_PRODUC_CLIENT',
    GET_OPERATION: 'GET_OPERATION',
    GET_OPERATION_ACT: 'GET_OPERATION_ACT',
    GET_PRODUCTS_OPERATION: 'GET_PRODUCTS_OPERATION',
}

const TextConstants = {
    REQUEST_TEXT: 'REQUEST_TEXT',
    FAILURE_TEXT: 'FAILURE_TEXT',
    SUCCESS_TEXT: 'SUCCESS_TEXT',
    GET_TEXT_CLIENT: 'GET_TEXT_CLIENT',
    GET_TEXTS: 'GET_TEXTS',
    GET_IMAGES: 'GET_IMAGES',
    GET_IMAGES_ACT: 'GET_IMAGES_ACT'
}

export {
    UserConstants,
    MailConstants,
    ClientConstants,
    TextConstants
};