-- MySQL Script generated by MySQL Workbench
-- Fri Apr 10 08:34:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema masivos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema masivos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `masivos` DEFAULT CHARACTER SET utf8 ;
USE `masivos` ;

-- -----------------------------------------------------
-- Table `masivos`.`correos_textos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `masivos`.`correos_textos` (
  `Id_texto` INT(11) NOT NULL AUTO_INCREMENT,
  `id_cliente` INT(11) NOT NULL,
  `subject` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `sender` VARCHAR(45) NULL DEFAULT 0,
  `body` TEXT NOT NULL,
  `individual` BIT(1) NULL DEFAULT 0,
  `suspendido` BIT(1) NULL DEFAULT 0,
  PRIMARY KEY (`Id_texto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `masivos`.`thread`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `masivos`.`thread` (
  `id_thread` INT(11) NOT NULL AUTO_INCREMENT,
  `Id_texto` INT(11) NOT NULL,
  `id_cliente` INT(11) NOT NULL,
  `id_producto` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `send` INT(11) NULL DEFAULT 0,
  `percentage` INT(11) NULL DEFAULT 0,
  `length` INT(11) NULL DEFAULT 0,
  `status` BIT(1) NULL DEFAULT 0,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_thread`),
  INDEX `fk_thread_correos_textos_idx` (`Id_texto` ASC) ,
  CONSTRAINT `fk_thread_correos_textos`
    FOREIGN KEY (`Id_texto`)
    REFERENCES `masivos`.`correos_textos` (`Id_texto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `masivos`.`outbound_correos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `masivos`.`outbound_correos` (
  `Id_outbound_correos` INT(11) NOT NULL AUTO_INCREMENT,
  `id_thread` INT(11) NOT NULL,
  `id_texto` INT(11) NOT NULL,
  `id_usuario_envia` INT(11) NOT NULL,
  `control` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `enviado` CHAR(1) NULL DEFAULT 0,
  `fecha_envio` TIMESTAMP NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`Id_outbound_correos`),
  INDEX `fk_outbound_correos_thread1_idx` (`id_thread` ASC) ,
  INDEX `fk_outbound_correos_correos_textos1_idx` (`id_texto` ASC) ,
  CONSTRAINT `fk_outbound_correos_thread1`
    FOREIGN KEY (`id_thread`)
    REFERENCES `masivos`.`thread` (`id_thread`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_outbound_correos_correos_textos1`
    FOREIGN KEY (`id_texto`)
    REFERENCES `masivos`.`correos_textos` (`Id_texto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
