-- MySQL Script generated by MySQL Workbench
-- Fri Apr 10 09:50:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oca_sac
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oca_sac
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oca_sac` DEFAULT CHARACTER SET utf8 ;
USE `oca_sac` ;

-- -----------------------------------------------------
-- Table `oca_sac`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oca_sac`.`usuarios` (
  `id_usuarios` INT(11) NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` INT(11) NOT NULL,
  PRIMARY KEY (`id_usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oca_sac`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oca_sac`.`clientes` (
  `id_cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `suspendido` BIT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oca_sac`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oca_sac`.`productos` (
  `id_producto` INT(11) NOT NULL AUTO_INCREMENT,
  `id_cliente` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `suspendido` BIT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_productos_clientes_idx` (`id_cliente` ASC) ,
  CONSTRAINT `fk_productos_clientes`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `oca_sac`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oca_sac`.`remesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oca_sac`.`remesas` (
  `id_remesa` INT(11) NOT NULL AUTO_INCREMENT,
  `id_cliente` INT(11) NOT NULL,
  `id_producto` INT(11) NOT NULL,
  PRIMARY KEY (`id_remesa`),
  INDEX `fk_remesas_clientes1_idx` (`id_cliente` ASC) ,
  INDEX `fk_remesas_productos1_idx` (`id_producto` ASC) ,
  CONSTRAINT `fk_remesas_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `oca_sac`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_remesas_productos1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `oca_sac`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oca_sac`.`gestiones_claves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oca_sac`.`gestiones_claves` (
  `id_gestiones_claves` INT(11) NOT NULL AUTO_INCREMENT,
  `gestiones_clavescol` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_gestiones_claves`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oca_sac`.`remesas_cuentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oca_sac`.`remesas_cuentas` (
  `id_remesas_cuentas` INT(11) NOT NULL AUTO_INCREMENT,
  `id_remesa` INT(11) NOT NULL,
  `no_linea` INT(11) NOT NULL,
  `id_gestiones_claves` INT(11) NOT NULL,
  `control` VARCHAR(45) NOT NULL,
  `nombre_completo` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_remesas_cuentas`),
  INDEX `fk_remesas_cuentas_remesas1_idx` (`id_remesa` ASC) ,
  INDEX `fk_remesas_cuentas_gestiones_claves1_idx` (`id_gestiones_claves` ASC) ,
  CONSTRAINT `fk_remesas_cuentas_remesas1`
    FOREIGN KEY (`id_remesa`)
    REFERENCES `oca_sac`.`remesas` (`id_remesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_remesas_cuentas_gestiones_claves1`
    FOREIGN KEY (`id_gestiones_claves`)
    REFERENCES `oca_sac`.`gestiones_claves` (`id_gestiones_claves`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oca_sac`.`remesas_cuentas_campos_adicionales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oca_sac`.`remesas_cuentas_campos_adicionales` (
  `id_remesas_cuentas_campos_adicionales` INT(11) NOT NULL AUTO_INCREMENT,
  `id_remesa` INT(11) NOT NULL,
  `no_linea` INT(11) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_remesas_cuentas_campos_adicionales`),
  INDEX `fk_remesas_cuentas_campos_adicionales_remesas1_idx` (`id_remesa` ASC) ,
  CONSTRAINT `fk_remesas_cuentas_campos_adicionales_remesas1`
    FOREIGN KEY (`id_remesa`)
    REFERENCES `oca_sac`.`remesas` (`id_remesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
